upstream lifera {
    server lifera:8080;
}

server {
    listen 80;
    server_name www.openautonomyx.com openautonomyx.com;

    location / {
        proxy_pass http://lifera;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /c/ {
        proxy_pass http://lifera;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /o/ {
        proxy_pass http://lifera;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}